Check list:

General:

[ ] Not exceed 1500 words.

[ ] No more than 5 figures/tables.

Introduction:

[ ] About 2-3 paragraphs.

[ ] A strong/convincing argument for the importance of this study, supported by peer-reviewed evidence (i.e. why this study is relevant to other people).  

[ ] Summaries of at least three peer-reviewed articles on the same area, topic, or question as this study. These should concisely describe the main conclusion/result in the context of the study sample.  

[ ] The research objective, goal, or question of this study is explicitly stated (i.e., what this study is going to do) and a strong connection is explicitly drawn between the literature summaries and this goal (i.e., how does the work of others fit into this goal/study).  

[ ] A brief but correct overview of the general statistical techniques that will be employed in the paper (i.e., what types of procedures will be used) and how these allow the research goal to be met.  

Methods:

[ ] About 2-3 paragraphs.

[ ] Not present any results or data summaries.

[ ] Correctly mentioning what type of statistical model(s) will be considered using appropriate course terminology.  

[ ] Correctly justifying why the statistical model(s) is/are appropriate for the problem, with specific reference to the type of data being considered and any other data properties that are relevant.  

[ ] Correctly explaining what predictor variables are considered of interest to the question and why other predictors are being included in the model.  

[ ] Correctly stating how it will be determined from the model(s) which predictors are significant and how much variation exists in the response.  

Results:

[ ] Statistical summaries of the variables considered in the analysis. These are appropriate/correct for the data being presented. Summaries should be univariate in nature (i.e., each variable separately) but may be supplemented by multivariate summaries if desired.  

[ ] A discussion of the statistical summaries presented, that correctly comments on at least one of the centre, spread or shape of each variable in the context of the sample population. Specific emphasis should be placed on the response distribution with correct commentary on all three of centre, spread and shape. If multivariate summaries are also presented, the discussion should describe how the relationship presented is relevant to the research problem.  

[ ] Presentation of the results of all statistical procedures applied to address the research question. Estimates from models should be presented with a corresponding measure of error/variability. Results of hypothesis tests should include the test statistic, the corresponding p-value and the significance level used.  

[ ] A discussion of the process involved in developing a suitable model that addresses the research goal. When referencing multiple models, descriptive language is used to aid the reader in distinguishing between them (e.g. avoid labelling models as “model 1, model 2”). Variables should be referred to conversationally and not using the names presented in R. Statistical procedures used should be explicitly stated, consistent with the methods section, and correctly applied. Evidence that supports decisions made towards developing a model that addresses the research goal must be referenced explicitly and used correctly. The discussion should flow logically, beginning with an initial model based on the cited literature and ending with the result that will be interpreted in the conclusion.  

Conclusion:

[ ] About 1-2 paragraphs.

[ ] Refer to figures/tables from the results section as needed (generally no new evidence is presented here).

[ ] A formal statistical interpretation of the effect on the response of at least one of the most important/relevant predictors in the chosen model and should be correct and in the context of the data.  

[ ] An informal interpretation of the model results, focusing on what the chosen model says about the relationship between predictors and response as a whole in this project. This should be consistent with the model results and in the context of the data.  

[ ] A comparison between the effects suggested by the model and the effects in the literature that was summarized earlier. The comparison should correctly address whether the effects from the model are supported by or contradictory to the literature, with in-text citations directing the reader to the relevant sources.  

[ ] A closing statement that highlights how the results of this study can be used to address the stated motivation from the introduction.  

Figures, Tables, and References:

[ ] The reference list/bibliography contains all source materials or articles mentioned in the written report. The list is well-formatted using an appropriate format (e.g., APA). In-text citations are included whenever information is summarized or mentioned from an external source (e.g. peer-reviewed article) and are in a consistent format as the reference list/bibliography.  

[ ] No R code is present in the written report (e.g. code that produces tables/figures), and R output (as displayed in the R console) is not present.  

[ ] Tables and figures include informative captions that cover 1) what is presented and 2) what is the key message the reader should take away. Captions should ensure that the reader does not need to have read the report itself to understand what is presented in the table/figure.  

[ ] Tables and figures are well designed (visually appealing, cohesive, and valuable). The information presented in each table/figure is easy to read and understand (e.g. avoids variable names from R, legible axis labels, etc.), makes sense to be presented in a single standalone unit, and is referenced and discussed in the main report text.  

--------------------------------------------------------------------------------
```{r}
#| echo: false
#| include: false
#| warning: false
#| message: false
#### Workspace setup ####
set.seed(912)
# List of necessary packages
packages <- c("ggplot2", "MASS", "pscl")
# Install missing packages
missing_packages <- packages[!(packages %in% installed.packages()[, "Package"])]
install.packages(missing_packages)
# Load packages
lapply(packages, library, character.only = TRUE)

#### Read data ####
load(here::here("portugal.RData"))
```

```{r}
summary(portugal)
```

```{r}
# Check for overdispersion.
mean(portugal$children)
sd(portugal$children)^2
```
```{r}
# Check for zero inflation.
hist(portugal$children)
```
```{r}
m1 <- glm(children ~ literacy + ageMarried + region + age + monthsSinceM, 
              family = poisson(link = "log"), 
              data = portugal)
m1_summ = cbind(est = m1$coef, confint(m1, level = 0.99))
knitr::kable(cbind(summary(m1)$coef,exp(m1_summ)), digits = 3)
summary(m1)
```

```{r}
m2 <- glm(children ~ literacy + ageMarried + region + age, 
                 family = poisson(link = "log"), 
                 data = portugal, 
                 offset = log(monthsSinceM + 0.000000000001))
m2_summ = cbind(est = m2$coef, confint(m2, level = 0.9))
knitr::kable(cbind(summary(m2)$coef,exp(m2_summ)), digits = 3)
```

```{r}
m3 <- glm(children ~ literacy + ageMarried+ age, 
                 family = poisson(link = "log"), 
                 data = portugal, 
                 offset = log(monthsSinceM + 0.000000000001))
lmtest::lrtest(m2, m3)
```

